//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flotta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class autokContext : DbContext
    {
        public autokContext()
            : base("name=autokContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autoktabla> autoktabla { get; set; }
        public virtual DbSet<felhtabla> felhtabla { get; set; }
        public virtual DbSet<muszakiallapottabla> muszakiallapottabla { get; set; }
        public virtual DbSet<soforautojatabla> soforautojatabla { get; set; }
        public virtual DbSet<szervizkonyvtabla> szervizkonyvtabla { get; set; }
    }
}
