//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flotta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soforautojatabla
    {
        public int idsoforAutoja { get; set; }
        public int idfelh { get; set; }
        public string rendszam { get; set; }
    
        public virtual autoktabla autoktabla { get; set; }
        public virtual felhtabla felhtabla { get; set; }
    }
}
