//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flotta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class szervizkonyvtabla
    {
        public int idszervizkonyv { get; set; }
        public string rendszamHOZ { get; set; }
        public System.DateTime idopont { get; set; }
        public string leiras { get; set; }
        public sbyte cascoE { get; set; }
        public sbyte biztositasE { get; set; }
    
        public virtual autoktabla autoktabla { get; set; }
    }
}
